### ISSUE TITLE
train the net

### ISSUE THREAD

**Issue by ptxaxx** [zhulf0804/NgeNet#7]
Hi！Thank you so much for sharing！
1:How many epochs has this been trained for? I didn't find any instructions on the source code，    
for epoch in range(config.max_epoch):
        print('=' * 20, epoch, '=' * 20)
        train_step, val_step = 0, 0
        for inputs in tqdm(train_dataloader):
            for k, v in inputs.items():
                if isinstance(v, list):
                    for i in range(len(v)):
                        inputs[k][i] = inputs[k][i].cuda()
                else:
                    inputs[k] = inputs[k].cuda()
2: Why is training so slow? my graphics card is titan

**Comment by zhulf0804** [comment]
Hi, thanks for your interest.

1. Different epochs are set for different datasets. The configuration can be seen in `configs/*.yaml` .
    For 3DMatch/3DLoMatch, max_epoch is set 40, which can be seen in https://github.com/zhulf0804/NgeNet/blob/d4917f22e55195132ec6fc602554102d321ce4b5/configs/threedmatch.yaml#L46
2. The low training speed is due to the correspondences construction operation (shown below) on CPU. For example, we trained 3DMatch on one RTX 3090 card using about 40 hours. 
https://github.com/zhulf0804/NgeNet/blob/d4917f22e55195132ec6fc602554102d321ce4b5/utils/o3d.py#L75-L88

Best regards.

**Comment by ptxaxx** [comment]
Thanks for such a quick answer！

**Comment by ptxaxx** [comment]
Hello, when I evaluate and visualize, the process is killed when it reaches 14%. It may be a memory overflow problem. Is there any good solution?my graphics card is titan

**Comment by zhulf0804** [comment]
Hello,

What's your GPU memory size ? I didn't record the runtime memory size before, but GTX 1080Ti is enough for me.

One way your can try is to use `torch.cuda.empty_cache()` after each iteration.

Best.

**Comment by ptxaxx** [comment]
&nbsp; &nbsp; Hi, sorry to trouble you again! Because I just started learning this aspect, so I don't understand a lot of things. I still can't solve the problem of killing the process. I don't know how to add this code. torch.cuda.empty_cache() ;&nbsp;
&nbsp; &nbsp; I executed this command. Is this not using CUDA?&nbsp;
&nbsp; &nbsp; python eval_3dmatch.py --benchmark 3DMatch --data_root your_path/indoor --checkpoint your_path/3dmatch.pth --saved_path work_dirs/3dmatch [--vis] [--no_cuda]
&nbsp; &nbsp; If I want to use CUDA for evaluation and visualization, how do I need to modify the code?
&nbsp; &nbsp; Hope to get your help, thank you very much！！！











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhulf0804/NgeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月26日(星期天) 中午12:19
***@***.***&gt;;
抄送:&nbsp;"夜 s ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhulf0804/NgeNet] train the net (Issue #7)





 
Hello,
 
What's your GPU memory size ? I didn't record the runtime memory size before, but GTX 1080Ti is enough for me.
 
One way your can try is to use torch.cuda.empty_cache() after each iteration.
 
Best.

**Comment by zhulf0804** [comment]
Hi, 
1. `python eval_3dmatch.py --benchmark 3DMatch --data_root your_path/indoor --checkpoint your_path/3dmatch.pth --saved_path work_dirs/3dmatch` menas using cuda for evaluation.
2. `python eval_3dmatch.py --benchmark 3DMatch --data_root your_path/indoor --checkpoint your_path/3dmatch.pth --saved_path work_dirs/3dmatch --vis` menas using cuda for visualization.
3. `python eval_3dmatch.py --benchmark 3DMatch --data_root your_path/indoor --checkpoint your_path/3dmatch.pth --saved_path work_dirs/3dmatch --vis --no_cuda` menas  visualizing on cpu.

Besides, you may add `torch.cuda.empty_cache()` in `line 199` as follows:
https://github.com/zhulf0804/NgeNet/blob/d4917f22e55195132ec6fc602554102d321ce4b5/eval_3dmatch.py#L194-L198

Best.
