### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by XMU-qcj** [zhulf0804/NgeNet#9]
Hello, thank you for your work, I encountered a problem, I used the pre-trained model and eval code provided by you to test, and I could not restore the effect provided by your paper on the MVP_RG data set. Where are the details that need to be changed for testing? ?

**Comment by zhulf0804** [comment]
Hello, thanks for your interest in this work.

There are some randomness in RANSAC operation. So we can get **a simiar result** when testing. The result on the MVP_RG reported in the paper is easy to reproduce, because we didn't report the best result which occurs occasionally.

We used **Open3d v0.10** to test. We found different performance were achived with different versions of Open3d, because RANSAC implemtations are different in differetn Open3d versions. What is your Open3D version?

**Comment by XMU-qcj** [comment]
> Hello, thanks for your interest in this work.
> 
> There are some randomness in RANSAC operation. So we can get **a simiar result** when testing. The result on the MVP_RG reported in the paper is easy to reproduce, because we didn't report the best result which occurs occasionally.
> 
> We used **Open3d v0.10** to test. We found different performance were achived with different versions of Open3d, because RANSAC implemtations are different in differetn Open3d versions. What is your Open3D version?

Yes, I realized the randomness, I am using the same version of open3d as you, and I have also done multiple tests, but still can't get good results, most of the rotation errors stay above 30. And I noticed that the number of npts set in your eval code is 768, will this affect the effect?

**Comment by zhulf0804** [comment]
Hello,
- `rotation errors stay above 30` is not reasonable, maybe there are improper operations.
-  the number of npts in the code affects, but it doesn't affect too much.

I tested twice just now with the README guidance (without modifying code), and the results (RRE 7.74 and 8.47) are as follows:

![mvp_rg_res](https://user-images.githubusercontent.com/36033208/182521946-4c1bbfd8-c902-4349-ad61-b274360c3689.png)

Did you test with the similar command ?

**Comment by XMU-qcj** [comment]
> Hello,
> 
> * `rotation errors stay above 30` is not reasonable, maybe there are improper operations.
> * the number of npts in the code affects, but it doesn't affect too much.
> 
> I tested twice just now with the README guidance (without modifying code), and the results (RRE 7.74 and 8.47) are as follows:
> 
> ![mvp_rg_res](https://user-images.githubusercontent.com/36033208/182521946-4c1bbfd8-c902-4349-ad61-b274360c3689.png)
> 
> Did you test with the similar command ?

I changed a server, used 3090 instead of 1080, and performed the same environment configuration and test, this time the result is excellent, which is very strange, but thank you for your reply

**Comment by zhulf0804** [comment]
Yes, it's strange.

We have tested the performance using different machines and GPUs, and achieved a similar performance.
